"""create lining assessment tables (lining_factors R0/R2/R7 + lining_reports)

Revision ID: 116
Revises: 115
"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "116"
down_revision: str | None = "115"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

FACTORS = [{'profile': 'rudnik',
  'code': 'R0.1',
  'group_code': 'R0',
  'name': 'R0.1 Доля работников, занятых на подземных работах, имеющих профильное горное высшее и среднее профессиональное '
          'образование',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'От 51 до 100% (0,00)'},
              {'value': 0.11, 'label': 'Менее 50% (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 0},
 {'profile': 'rudnik',
  'code': 'R0.2',
  'group_code': 'R0',
  'name': 'R0.2 Доля ИТР добычных и проходческих участков, участка ПВС, имеющих профильное горное образование и стаж работы на '
          'инженерных должностях более трех лет',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Более 90% (0,00)'},
              {'value': 0.11, 'label': 'От 70 до 89 % (0,11)'},
              {'value': 0.22, 'label': 'Менее 69% (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 1},
 {'profile': 'rudnik',
  'code': 'R0.3',
  'group_code': 'R0',
  'name': 'R0.3 Доля ИТР, обученных в течение трех последних лет по программам повышения квалификации (профессиональной '
          'переподготовки) в области технологии и безопасности подземных горных работ',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Более 75% (0,00)'},
              {'value': 0.11, 'label': 'От 50 до 74 % (0,11)'},
              {'value': 0.22, 'label': 'Менее 49% (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 2},
 {'profile': 'rudnik',
  'code': 'R0.4',
  'group_code': 'R0',
  'name': 'R0.4 Проведение учебных тренировок с работниками рудника по действиям в случае аварии или инцидента',
  'max_score': 0.56,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Учебные тренировки проводятся (0,00)'},
              {'value': 0.56, 'label': 'Учебные тренировки не проводятся (0,56)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 3},
 {'profile': 'rudnik',
  'code': 'R0.5',
  'group_code': 'R0',
  'name': 'R0.5 Соблюдение установленной периодичности проведения учебных тренировок включения в самоспасатель со всеми '
          'работниками (включая работников подрядных организаций)',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Периодичность соблюдается (0,00)'},
              {'value': 0.11, 'label': 'Периодичность не соблюдается (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 4},
 {'profile': 'rudnik',
  'code': 'R0.6',
  'group_code': 'R0',
  'name': 'R0.6 Факт наличия собственного учебного полигона «Дымный штрек» и проведения на нем учебных тренировок',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Да (0,00)'},
              {'value': 0.11, 'label': 'Нет (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 5},
 {'profile': 'rudnik',
  'code': 'R0.7',
  'group_code': 'R0',
  'name': 'R0.7 Факт проведения в течение 5 последних лет оценки профессиональных рисков на подземных рабочих местах и '
          'ознакомления работников с ее результатами',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Да (0,00)'},
              {'value': 0.11, 'label': 'Нет (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 6},
 {'profile': 'rudnik',
  'code': 'R0.8',
  'group_code': 'R0',
  'name': 'R0.8 Укомплектованность добычных и проходческих участков, участка ПВС (службы ПБ и СППДЯ) ИТР (по отношению к '
          'требуемой численности)',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Более 90% (0,00)'},
              {'value': 0.11, 'label': 'От 70 до 89 % (0,11)'},
              {'value': 0.22, 'label': '69% и менее (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 7},
 {'profile': 'rudnik',
  'code': 'R0.9',
  'group_code': 'R0',
  'name': 'R0.9 Соответствие штата работников участка ПВС проектной численности',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Соответствует проектной численности (0,00)'},
              {'value': 0.11, 'label': 'Не соответствует проектной численности (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 8},
 {'profile': 'rudnik',
  'code': 'R0.10',
  'group_code': 'R0',
  'name': 'R0.10 Соответствие штата работников добычного участка проектной численности',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Соответствует проектной численности (0,00)'},
              {'value': 0.11, 'label': 'Не соответствует проектной численности (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 9},
 {'profile': 'rudnik',
  'code': 'R0.11',
  'group_code': 'R0',
  'name': 'R0.11 Соответствие штата работников проходческого участка проектной численности',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Соответствует проектной численности (0,00)'},
              {'value': 0.11, 'label': 'Не соответствует проектной численности (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 10},
 {'profile': 'rudnik',
  'code': 'R0.12',
  'group_code': 'R0',
  'name': 'R0.12 Соответствие штата работников участка профилактики и дегазации проектной численности',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Соответствует проектной численности (0,00)'},
              {'value': 0.11, 'label': 'Не соответствует проектной численности (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 11},
 {'profile': 'rudnik',
  'code': 'R0.13',
  'group_code': 'R0',
  'name': 'R0.13 Соответствие штата работников участка шахтного транспорта материалов и персонала проектной численности',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Соответствует проектной численности (0,00)'},
              {'value': 0.11, 'label': 'Не соответствует проектной численности (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 12},
 {'profile': 'rudnik',
  'code': 'R0.14',
  'group_code': 'R0',
  'name': 'R0.14 Привлечение подрядных организаций для работы в руднике',
  'max_score': 0.56,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Подрядные организации не привлекаются (0,00)'},
              {'value': 0.56, 'label': 'Подрядные организации привлекаются (0,56)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 13},
 {'profile': 'rudnik',
  'code': 'R0.15',
  'group_code': 'R0',
  'name': 'R0.15 Уровень обеспечения работников СИЗ, инструментами и материалами, необходимыми для безопасного труда',
  'max_score': 0.34,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Обеспечение производится в полной мере (0,00)'},
              {'value': 0.34, 'label': 'Обеспечение производится частично или не производится (0,34)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 14},
 {'profile': 'rudnik',
  'code': 'R0.16',
  'group_code': 'R0',
  'name': 'R0.16 Обеспечение всех работников индивидуально закрепленными самоспасателями',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Да (0,00)'},
              {'value': 0.11, 'label': 'Нет (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 15},
 {'profile': 'rudnik',
  'code': 'R0.17',
  'group_code': 'R0',
  'name': 'R0.17 Организация на руднике проведения предсменных и послесменных медицинских осмотров',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0,
               'label': 'Осмотры проводятся работниками здравпункта, в том числе с применением средств автоматизированного '
                        'контроля (0,00)'},
              {'value': 0.22, 'label': 'Осмотры проводятся по формальному принципу или не проводятся (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 16},
 {'profile': 'rudnik',
  'code': 'R0.18',
  'group_code': 'R0',
  'name': 'R0.18 Организация проведения предсменного и послесменного выявления работников в состоянии алкогольного или '
          'наркотического опьянения',
  'max_score': 1.12,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Проводятся в полном объеме (0,00)'},
              {'value': 0.56, 'label': 'Проводятся не в полном объеме (0,56)'},
              {'value': 1.12, 'label': 'Не проводятся (1,12)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 17},
 {'profile': 'rudnik',
  'code': 'R0.19',
  'group_code': 'R0',
  'name': 'R0.19 Проведение первичных (при приеме на работу) и плановых (не реже 1 раза в 5 лет) психиатрических '
          'освидетельствований работников',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Освидетельствования проводятся (0,00)'},
              {'value': 0.11, 'label': 'Освидетельствования не проводятся (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 18},
 {'profile': 'rudnik',
  'code': 'R0.20',
  'group_code': 'R0',
  'name': 'R0.20 Проведение в организации аудита безопасности не реже 1 раза за 3 года',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Аудит проводится (0,00)'},
              {'value': 0.22, 'label': 'Аудит не проводится (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 19},
 {'profile': 'rudnik',
  'code': 'R0.21',
  'group_code': 'R0',
  'name': 'R0.21 Проведение в организации общественного контроля уполномоченными лицами по охране труда',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Общественный контроль проводится (0,00)'},
              {'value': 0.11, 'label': 'Общественный контроль не проводится (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 20},
 {'profile': 'rudnik',
  'code': 'R0.22',
  'group_code': 'R0',
  'name': 'R0.22 Использование средств видеофиксации (видеорегистраторов) на подземных рабочих местах, находящихся в пределах '
          'зон повышенной опасности',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0,
               'label': 'Средства видеофиксации используются на всех рабочих местах, находящихся в пределах опасных зон (0,00)'},
              {'value': 0.11,
               'label': 'Средства видеофиксации используются на отдельных рабочих местах, находящихся в пределах опасных зон '
                        '(0,11)'},
              {'value': 0.22, 'label': 'Средства видеофиксации не используются (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 21},
 {'profile': 'rudnik',
  'code': 'R0.23',
  'group_code': 'R0',
  'name': 'R0.23 Факт наличия системы наблюдения, оповещения, связи и поддержки действий персонала в случае аварий',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Да (0,00)'},
              {'value': 0.11, 'label': 'Нет (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 22},
 {'profile': 'rudnik',
  'code': 'R0.24',
  'group_code': 'R0',
  'name': 'R0.24 Факт наличия предусмотренных мер по защите жизни и здоровья работников в случае аварии',
  'max_score': 0.11,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Да (0,00)'},
              {'value': 0.11, 'label': 'Нет (0,11)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 23},
 {'profile': 'rudnik',
  'code': 'R0.25',
  'group_code': 'R0',
  'name': 'R0.25 Факт наличия в структуре заработной платы условно-постоянной части (не менее 70 %), не зависящей от выработки '
          'труда, но зависящей от показателей безопасности',
  'max_score': 0.56,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Да (0,00)'},
              {'value': 0.56, 'label': 'Нет (0,56)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 24},
 {'profile': 'rudnik',
  'code': 'R0.26',
  'group_code': 'R0',
  'name': 'R0.26 Факт наличия в Положении о заработной плате мер поощрения и мер административного воздействия за нарушение '
          'правил в областях промышленной безопасности и охраны труда',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Да (0,00)'},
              {'value': 0.22, 'label': 'Нет (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 25},
 {'profile': 'rudnik',
  'code': 'R0.27',
  'group_code': 'R0',
  'name': 'R0.27 Количество несчастных случаев, произошедших за последний год по причине совершения работниками опасных действий',
  'max_score': 0.34,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Несчастных случаев не зарегистрировано (0,00)'},
              {'value': 0.22, 'label': 'От 1 до 2 несчастных случаев (0,22)'},
              {'value': 0.34, 'label': 'Более 3 несчастных случаев (0,34)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 26},
 {'profile': 'rudnik',
  'code': 'R0.28',
  'group_code': 'R0',
  'name': 'R0.28 Количество несчастных случаев, произошедших за последний год по причине неприменения работниками средств '
          'индивидуальной защиты',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Несчастных случаев не зарегистрировано (0,00)'},
              {'value': 0.11, 'label': 'От 1 до 2 несчастных случаев (0,11)'},
              {'value': 0.22, 'label': 'Более 3 несчастных случаев (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 27},
 {'profile': 'rudnik',
  'code': 'R0.29',
  'group_code': 'R0',
  'name': 'R0.29 Уровень опасности нарушений, выявленных за последний год инспекторами Ростехнадзора',
  'max_score': 0.34,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Нарушения могут быть устранены в ходе проверки (или нарушений не выявлено) (0,00)'},
              {'value': 0.11,
               'label': 'Минимум одно нарушение имеет срок устранения, но не требует остановки горных работ (0,11)'},
              {'value': 0.34, 'label': 'Минимум одно нарушение имеет срок устранения и требует остановку горных работ (0,34)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 28},
 {'profile': 'rudnik',
  'code': 'R0.30',
  'group_code': 'R0',
  'name': 'R0.30 Коэффициент устраняемости нарушений в области промышленной безопасности Kустр, доли ед. Kустр=Nустр/Nнар.об. '
          'где Nустр - количество устраненных в срок нарушений, выявленных инспекторами Ростехнадзора за последний год, нар.; '
          'Nнар.об. - количество нарушений, выявленных инспекторами Ростехнадзора за последний год, нар.',
  'max_score': 1.12,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': '0,9<Кустр≤1,0 (0,00)'},
              {'value': 0.45, 'label': '0,5<Кустр≤0,9 (0,45)'},
              {'value': 0.9, 'label': '0,3<Кустр≤0,5 (0,90)'},
              {'value': 1.12, 'label': 'Кустр≤0,3 (1,12)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 29},
 {'profile': 'rudnik',
  'code': 'R2.1',
  'group_code': 'R2',
  'name': 'R2.1 Отработка блоков (участков), склонных или опасных по горным ударам',
  'max_score': 0.16,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Не отрабатываются склонные или опасные по горным ударам блоки (участки) (0,00)'},
              {'value': 0.1, 'label': 'Шахта отрабатывает минимум 1 пласт, угрожаемый по горным ударам (0,10)'},
              {'value': 0.16, 'label': 'Шахта отрабатывает минимум 1 пласт, опасный по горным ударам (0,16)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 30},
 {'profile': 'rudnik',
  'code': 'R2.2',
  'group_code': 'R2',
  'name': 'R2.2 Применение локальных способов предотвращения горных ударов',
  'max_score': 0.1,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Локальные способы применяются (0,00)'},
              {'value': 0.1, 'label': 'Локальные способы не применяются (0,10)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 31},
 {'profile': 'rudnik',
  'code': 'R2.3',
  'group_code': 'R2',
  'name': 'R2.3 Применение региональных способов предотвращения горных ударов (кроме подработки и надработки)',
  'max_score': 0.16,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Региональные способы применяются (0,00)'},
              {'value': 0.16, 'label': 'Региональные способы не применяются (0,16)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 32},
 {'profile': 'rudnik',
  'code': 'R2.4',
  'group_code': 'R2',
  'name': 'R2.4 Применение защитной подработки или надработки',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Подработка или надработка применяется (0,00)'},
              {'value': 0.22, 'label': 'Подработка или надработка не применяется (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 33},
 {'profile': 'rudnik',
  'code': 'R2.5',
  'group_code': 'R2',
  'name': 'R2.5 Ведение горных работ в зонах ПГД',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Работы в зонах ПГД не ведутся (0,00)'},
              {'value': 0.22, 'label': 'Работы в зонах ПГД ведутся (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 34},
 {'profile': 'rudnik',
  'code': 'R2.6',
  'group_code': 'R2',
  'name': 'R2.6 Ведение горных работ в зонах влияния геологических нарушений',
  'max_score': 0.16,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Работы в зонах влияния геологических нарушений не ведутся (0,00)'},
              {'value': 0.16, 'label': 'Работы в зонах влияния геологических нарушений ведутся (0,16)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 35},
 {'profile': 'rudnik',
  'code': 'R2.7',
  'group_code': 'R2',
  'name': 'R2.7 Применение локальных или региональных мероприятий по предотвращению горных ударов в части ведения горных работ в '
          'зонах ПГД и в зонах влияния геологических нарушений',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0,
               'label': 'Мероприятия применяются или работы в зонах ПГД, в зонах влияния геологических нарушений не ведутся '
                        '(0,00)'},
              {'value': 0.22, 'label': 'Мероприятия не применяются (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 36},
 {'profile': 'rudnik',
  'code': 'R2.8',
  'group_code': 'R2',
  'name': 'R2.8 Факт перехода передовых диагональных выработок',
  'max_score': 0.16,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Нет (0,00)'},
              {'value': 0.16, 'label': 'Да (0,16)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 37},
 {'profile': 'rudnik',
  'code': 'R2.9',
  'group_code': 'R2',
  'name': 'R2.9 Реализация контроля и прогноза динамических явлений в рамках МФСБ',
  'max_score': 0.16,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Реализован контроль и прогноз динамических явлений в рамках МФСБ (0,00)'},
              {'value': 0.16, 'label': 'Не реализован контроль и прогноз динамических явлений в рамках МФСБ (0,16)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 38},
 {'profile': 'rudnik',
  'code': 'R2.10',
  'group_code': 'R2',
  'name': 'R2.10 Проведение текущего прогноза состояния горного массива',
  'max_score': 0.03,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Текущий прогноз проводится (0,00)'},
              {'value': 0.03, 'label': 'Текущий прогноз не проводится (0,03)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 39},
 {'profile': 'rudnik',
  'code': 'R2.11',
  'group_code': 'R2',
  'name': 'R2.11 Проведение локального прогноза состояния горного массива',
  'max_score': 0.1,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Локальный прогноз проводится (0,00)'},
              {'value': 0.1, 'label': 'Локальный прогноз не проводится (0,10)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 40},
 {'profile': 'rudnik',
  'code': 'R2.12',
  'group_code': 'R2',
  'name': 'R2.12 Проведение регионального прогноза состояния горного массива',
  'max_score': 0.22,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Региональный прогноз проводится (0,00)'},
              {'value': 0.22, 'label': 'Региональный прогноз не проводится (0,22)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 41},
 {'profile': 'rudnik',
  'code': 'R2.13',
  'group_code': 'R2',
  'name': 'R2.13 Количество горных ударов/ДРПВ, зарегистрированных за последние 3 года',
  'max_score': 0.64,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Горные удары/ДРПВ не зарегистрированы (0,00)'},
              {'value': 0.48, 'label': 'Зарегистрирован 1 горный удар/ДРПВ (0,48)'},
              {'value': 0.64, 'label': 'Зарегистрированы 2 горных удара/ДРПВ и более (0,64)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 42},
 {'profile': 'rudnik',
  'code': 'R2.14',
  'group_code': 'R2',
  'name': 'R2.14 Наличие людей, травмированных в результате горных ударов/ДРПВ за последние 3 года',
  'max_score': 0.64,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Травмированные в результате горных ударов/ДРПВ отсутствуют (0,00)'},
              {'value': 0.48, 'label': 'В результате горных ударов/ДРПВ травмирован 1 человек и более (0,48)'},
              {'value': 0.64, 'label': 'В результате горных ударов/ДРПВ смертельно травмирован 1 человек и более (0,64)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 43},
 {'profile': 'rudnik',
  'code': 'R7.1',
  'group_code': 'R7',
  'name': 'R7.1 Ведение горных работ в блоках (участках) с неустойчивой непосредственной кровлей',
  'max_score': 2.69,
  'default_value': 0.0,
  'options': [{'value': 0.0,
               'label': 'Горные работы не ведутся в блоках (участках) с неустойчивой непосредственной кровлей (0,00)'},
              {'value': 2.69, 'label': 'Отрабатывается минимум один пласт с неустойчивой непосредственной кровлей (2,69)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 44},
 {'profile': 'rudnik',
  'code': 'R7.2',
  'group_code': 'R7',
  'name': 'R7.2 Ведение горных работ в зонах ПГД',
  'max_score': 1.88,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Работы в зонах ПГД не ведутся (0,00)'},
              {'value': 1.88, 'label': 'Работы в зонах ПГД ведутся (1,88)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 45},
 {'profile': 'rudnik',
  'code': 'R7.3',
  'group_code': 'R7',
  'name': 'R7.3 Ведение горных работ в зонах влияния геологических нарушений',
  'max_score': 1.88,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Работы в зонах влияния геологических нарушений не ведутся (0,00)'},
              {'value': 1.88, 'label': 'Работы в зонах влияния геологических нарушений ведутся (1,88)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 46},
 {'profile': 'rudnik',
  'code': 'R7.4',
  'group_code': 'R7',
  'name': 'R7.4 Факт отработки пластов по мощности или наличия опасности отжима угля',
  'max_score': 2.69,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': '<2,5 м (0,00)'},
              {'value': 1.0, 'label': '2,5÷3,5 м (1,00)'},
              {'value': 2.0, 'label': '3,5÷4,5 м (2,00)'},
              {'value': 2.69, 'label': '>4,5 м (2,69)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 47},
 {'profile': 'rudnik',
  'code': 'R7.5',
  'group_code': 'R7',
  'name': 'R7.5 Применение локальных мероприятий по предотвращению обрушений',
  'max_score': 0.81,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Локальные способы применяются (0,00)'},
              {'value': 0.81, 'label': 'Локальные способы не применяются (0,81)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 48},
 {'profile': 'rudnik',
  'code': 'R7.6',
  'group_code': 'R7',
  'name': 'R7.6 Проведение периодического инструментального (визуального) контроля состояния кровли с выдачей предписаний и их '
          'исполнением',
  'max_score': 1.35,
  'default_value': 0.0,
  'options': [{'value': 0.0,
               'label': 'Контроль проводится (или отсутствуют пласты с неустойчивой кровлей, не ведутся работы в зонах ПГД и '
                        'зонах влияния геологических нарушений) (0,00)'},
              {'value': 1.35, 'label': 'Контроль не проводится (1,35)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 49},
 {'profile': 'rudnik',
  'code': 'R7.7',
  'group_code': 'R7',
  'name': 'R7.7 Реализация контроля состояния кровли горных выработок в рамках МФСБ',
  'max_score': 1.35,
  'default_value': 0.0,
  'options': [{'value': 0.0,
               'label': 'Реализован контроль кровли горных выработок в рамках МФСБ (или отсутствуют пласты с неустойчивой '
                        'кровлей, не ведутся работы в зонах ПГД и зонах влияния геологических нарушений) (0,00)'},
              {'value': 1.35, 'label': 'Не реализован контроль состояния кровли горных выработок в рамках МФСБ (1,35)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 50},
 {'profile': 'rudnik',
  'code': 'R7.8',
  'group_code': 'R7',
  'name': 'R7.8 Проведение инженерно-геологических изысканий для определения физико-механических свойств пород кровли (при '
          'каждой засечке выработки и по длине выработки с установленной периодичностью)',
  'max_score': 0.54,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Изыскания проводятся (0,00)'},
              {'value': 0.54, 'label': 'Изыскания не проводятся (0,54)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 51},
 {'profile': 'rudnik',
  'code': 'R7.9',
  'group_code': 'R7',
  'name': 'R7.9 Проведение инженерно-геологических изысканий для оценки состояния пород кровли посредством применения '
          'видеоэндоскопа при изменении горно-геологических условий и состояния крепи выработки',
  'max_score': 0.54,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Изыскания проводятся (0,00)'},
              {'value': 0.54, 'label': 'Изыскания не проводятся (0,54)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 52},
 {'profile': 'rudnik',
  'code': 'R7.10',
  'group_code': 'R7',
  'name': 'R7.10 Количество нарушений паспортов крепления горных выработок, выявленных инспекторами Ростехнадзора за прошедший '
          'год',
  'max_score': 0.54,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Нарушений не выявлено (0,00)'},
              {'value': 0.27, 'label': 'Выявлено 1 нарушение (0,27)'},
              {'value': 0.54, 'label': 'Выявлено 2 нарушения и более (0,54)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 53},
 {'profile': 'rudnik',
  'code': 'R7.11',
  'group_code': 'R7',
  'name': 'R7.11 Количество обрушений горных пород, зарегистрированных за последние 3 года',
  'max_score': 5.38,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Обрушения не зарегистрированы (0,00)'},
              {'value': 4.04, 'label': 'Зарегистрировано 1 обрушение (4,04)'},
              {'value': 5.38, 'label': 'Зарегистрированы 2 обрушения и более (5,38)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 54},
 {'profile': 'rudnik',
  'code': 'R7.12',
  'group_code': 'R7',
  'name': 'R7.12 Наличие людей, травмированных в результате обрушений горных пород за последние 3 года',
  'max_score': 5.38,
  'default_value': 0.0,
  'options': [{'value': 0.0, 'label': 'Травмированные в результате обрушений отсутствуют (0,00)'},
              {'value': 4.04, 'label': 'В результате обрушений травмирован 1 человек и более (4,04)'},
              {'value': 5.38, 'label': 'В результате обрушений смертельно травмирован 1 человек и более (5,38)'},
              {'value': None, 'label': 'Нет (без оценки)'}],
  'sort_order': 55}]


def upgrade() -> None:
    op.create_table(
        "lining_factors",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("profile", sa.String(length=10), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("group_code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("max_score", sa.Float(), nullable=False, server_default="0"),
        sa.Column("default_value", sa.Float(), nullable=True),
        sa.Column("options", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.UniqueConstraint("profile", "code", name="uq_lining_factor_profile_code"),
    )
    op.create_index("ix_lining_factors_profile", "lining_factors", ["profile"])
    table = sa.table(
        "lining_factors",
        sa.column("profile", sa.String),
        sa.column("code", sa.String),
        sa.column("group_code", sa.String),
        sa.column("name", sa.Text),
        sa.column("max_score", sa.Float),
        sa.column("default_value", sa.Float),
        sa.column("options", postgresql.JSONB),
        sa.column("sort_order", sa.Integer),
    )
    op.bulk_insert(table, FACTORS)

    op.create_table(
        "lining_reports",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("expert_id", sa.Integer(), sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False, server_default=""),
        sa.Column("selections", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("element_categories", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("expert_scores", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("service_life_years", sa.Float(), nullable=False, server_default="5"),
        sa.Column("header", postgresql.JSONB(), nullable=False, server_default="{}"),
        sa.Column("blocks", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("overall_r", sa.Float(), nullable=False, server_default="0"),
        sa.Column("overall_category", sa.String(length=120), nullable=False, server_default=""),
        sa.Column("final_capital", sa.Float(), nullable=False, server_default="0"),
        sa.Column("final_emergency", sa.Float(), nullable=False, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    )
    op.create_index("ix_lining_reports_expert_id", "lining_reports", ["expert_id"])


def downgrade() -> None:
    op.drop_index("ix_lining_reports_expert_id", table_name="lining_reports")
    op.drop_table("lining_reports")
    op.drop_index("ix_lining_factors_profile", table_name="lining_factors")
    op.drop_table("lining_factors")
